#!/bin/bash

# Nama virtual environment
VENV_NAME="venv"

# Periksa apakah virtual environment sudah ada dan buat jika belum
if [ ! -d "$VENV_NAME" ]; then
  echo "Membuat virtual environment..."
  python3 -m venv "$VENV_NAME" || { echo "Gagal membuat virtual environment"; exit 1; }
fi

# Aktifkan virtual environment
echo "Mengaktifkan virtual environment..."
source "$VENV_NAME/bin/activate" || { echo "Gagal mengaktifkan virtual environment"; exit 1; }

# Periksa keberadaan file requirements.txt dan instal dependensi jika ada
if [ -f requirements.txt ]; then
  echo "Menginstal dependensi..."
  pip install -r requirements.txt || { echo "Gagal menginstal dependensi"; exit 1; }
fi

# Jalankan bot
echo "Menjalankan bot..."
python3 main.py

# Nonaktifkan virtual environment setelah selesai (opsional)
echo "Menonaktifkan virtual environment..."
deactivate
